[package]
name = "proteoseek"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
forust = "0.1.0"
gbdt = "0.1.3"
perpetual = "0.10.0"
rayon = "1.11.0"
smartcore = "0.4.8"
